#-------------------------------------------------------------------------------
# Plugins
#-------------------------------------------------------------------------------

plugins:
  - jekyll-paginate

#-------------------------------------------------------------------------------
# Site settings
#-------------------------------------------------------------------------------

title: "Appkr.memo(new Life)"

description: "appkr's blog to record day-to-day life & thoughts."
baseurl: ""
url: "https://blog.appkr.dev"

excerpt_separator: <!--more-->

#-------------------------------------------------------------------------------
# Contacts
#-------------------------------------------------------------------------------

author: "appkr"
email: "juwonkim@me.com"

#-------------------------------------------------------------------------------
# Build settings
#-------------------------------------------------------------------------------

exclude:
  - lib
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower.json
  - gulpfile.babel.js
  - package.json
  - publish.sh
  - public
  - yarn.lock

permalink: /:categories/:slug/
lsi: false

#-------------------------------------------------------------------------------
# Outputting
#-------------------------------------------------------------------------------

paginate: 5
paginate_path: /page:num/
destination: public
