# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Site settings
title: "Appkr.memo(new Life)"

description: "appkr's blog to record day-to-day life & thoughts."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.appkr.kr" # the base hostname & protocol for your site

excerpt_separator: <!--more-->

# Contacts
author: "appkr"
email: "juwonkim@me.com"
github: "https://github.com/appkr"
facebook: "https://www.facebook.com/juwonkimatmedotcom"
twitter:
googleplus:
youtube:
stackoverflow:
flickr:
dribbble:
instagram:
linkedin:
pinterest:

# Build settings
exclude:
  - lib
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower.json
  - gulpfile.babel.js
  - package.json
permalink: /:categories/:slug/
lsi: false # if set to true generate related posts

# Conversion
markdown: redcarpet
redcarpet:
  extensions:
    - smart
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - underline
    - highlight
    - quote
    - footnote_ref
  highlighter: pygments

# Outputting
paginate: 5
paginate_path: /page:num/
destination: public

# Services
disqus_short_name: appkr
google_tracking_id: UA-72812647-1

